#jar 시킬때 파람을 줘서 job을 실행 시킬 수 있다. none은 jar을 시행할때 어떤 파람을 안주면 실행을 안하게 설정
spring.batch.job.names: ${job.name:NONE}

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000

  datasource:
#    hikari:
#      jdbc-url: jdbc:h2:tcp://localhost/~/batch;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      username: sa
#      password:
#      driver-class-name: org.h2.Driver
    ###
    url: jdbc:h2:tcp://localhost/~/batch;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    # 위 주석을 풀면 아래와 같은 경고가 나온다. JPA does not support custom isolation levels, so locks may not be taken when launching Jobs
    # 위 주석을 유지하고 돌리면 Invocation of destroy method failed on bean with name 'inMemoryDatabaseShutdownExecutor': org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-200]
    # 아래와 같은 경고가 나온다. 확인이 필요하다.

  main:
    allow-bean-definition-overriding: true


  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

logging.level:
  org.hibernate.SQL: debug